- name: Create DS2 DB oVirt VMs
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    how_many: 1
    engine_url: https://engine.example.com/ovirt-engine/api
    engine_user: admin@internal
    template_name: rhodain-template

    db_vm_tag: ds-mysql
    db_ds2_vm_tag: ds2-mysql-50gb

    ds2_db_vm:
      name: "ds2-mysql-{{ item }}"
      tag: "{{ db_ds2_vm_tag }}"
      profile:
        state: running
        cluster: Default
        template: "{{ template_name }}"
        clone: yes
        operating_system: rhel_7x64
        placement_policy: migratable
        type: server
        memory: 8GiB
        memory_guaranteed: 8GiB
        memory_max: 8GiB
        cpu_cores: 4
        cpu_sockets: 1
        io_threads: 2
        ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAOAqqV8jfqo9xFDJ4DfDdVkrCAzQaEZOQey/CFK2ZUeO0nHehMGminapv6PeHLA/yijC9RXfozTowYaZmKfa1K23u0BFFMSb86dJmBWZNia+LPHb/vTpyZkCT/qXV5z9GmZalHJ8Ia1jREkUyrlulOLricW39RMNlHKvsOKZqAgnaZFudDSxKgsGEWS6oqqWqBH7A/fgjBMGBZtQBriqQT3ddFM2BqO4iMMHQfos+977fc4iGL12nI1rH1y7neUtX119mKpgmYCRtgy6soSwzeLe027LJUyF7DUWae54NgepSuHXxsHvsUbDUQKgJI3nwhjqeoEIJCZ/k5btbq3g3 root@rhvh4.example.com
        graphical_console:
          protocol:
            - spice
            - vnc
        cloud_init_persist: false
        cloud_init:
          nic_ip_address: "10.227.17.{{ item | int }}"
          nic_gateway: 10.227.16.1
          nic_netmask: 255.255.252.0
          nic_on_boot: true
          nic_name: eth0
          nic_boot_protocol: static
          host_name: "ds2-mysql-{{ item }}"
          dns_search: example.com
          user_name: root
          root_password: "RedHat1!"

  tasks:

    - include_vars: credentials/ovirt-credentials.yaml

    - assert:
        that:
          - how_many is defined
          - engine_url is defined
          - engine_user is defined
          - engine_password is defined

    - ovirt_auth:
        url: "{{ engine_url }}"
        username: "{{ engine_user }}"
        password: "{{ engine_password }}"

    - set_fact:
        ds2_db_vms: "{{ (ds2_db_vms | default([])) + [ds2_db_vm] }}"
      with_sequence: "start=1 count={{ how_many }}"

    - name: Create DS2 DB oVirt VMs
      include_role: name=ovirt-ansible-vm-infra
      vars:
        debug_vm_create: true
        vm_infra_create_single_timeout: 800
        vms: "{{ ds2_db_vms }}"
        wait_for_ip: false

    - name: Tag DS2 database VMs with {{ db_vm_tag }}
      ovirt_tags:
        auth: "{{ ovirt_auth }}"
        name: "{{ db_vm_tag }}"
        vms: "{{ ds2_db_vms | map(attribute='name') | list }}"

