---

- hosts: load-drivers

  roles:
    - rhsm-registered
    - monitoring
    - chronyd

  vars:
    required_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
    interface: ens192  

  tasks:

   - name: Disable all repositories except required_repos
     rhsm_repository:
       name: "{{ enabled_repos.repositories |
        map(attribute='id') |
        difference(required_repos) |
        join(',' ) }}"
       state: disabled

   - name: enable required repositories
     rhsm_repository: name={{ required_repos | join(',') }}
     state: enabled
     register: enabled_repos

   - name: enable extra repo
     rhsm_repository: name="rhel-7-server-extras-rpms"
     state: enabled

   - name: install docker and ansible dependencies
     package: name={{ item }} state=present
     with_items:
       - docker
       - docker-python

   - name: start and enable docker
     service:
       name: docker
       state: started
       enabled: yes

   - name: pull down load driver containers
     docker_image: name={{ item }}
     with_items:
        - dmesser/ds2mysqldriver
        - dmesser/ds3webdriver

   - name: install python dependencies
     package: name={{ item }} state=present
     with_items:
       - MySQL-python

   - name: copy the benchmark script
     copy:
        src: files/run_bench.py
        dest: /root/
        owner: root
        group: root
        mode: 0755

   - name: create the directory for the ds2 config files
     file: path=/root/ds2mysqldriver state=directory

   - name: create the directory for the ds3 config files
     file: path=/root/ds3mysqldriver state=directory

   - name: Copy collectd config file
     template:
       src: network-bandwidth-usage.conf.j2
       dest: /etc/collectd.d/network-bandwidth-usage.conf
       owner: root
       group: root
       mode: 0644

- hosts: rhel24.poc4.maxta.com

  tasks:

   - name: create config files for the containers
     template:
         src: templates/DriverConfig.txt.j2
         dest: /root/ds2mysqldriver/DriverConfig.txt.{{ item.0 }}
         owner: root
         group: root
         mode: 0644
     loop: "{{ range(0,51,1)|list|zip(range(1,250,3))|list }}"

- hosts: rhel26.poc4.maxta.com

  tasks:

   - name: create config files for the containers
     template:
         src: templates/DriverConfig.txt.j2
         dest: /root/ds2mysqldriver/DriverConfig.txt.{{ item.0 }}
         owner: root
         group: root
         mode: 0644
     loop: "{{ range(0,51,1)|list|zip(range(2,250,3))|list }}"

- hosts: rhel28.poc4.maxta.com

  tasks:

   - name: create config files for the containers
     template:
         src: templates/DriverConfig.txt.j2
         dest: /root/ds2mysqldriver/DriverConfig.txt.{{ item.0 }}
         owner: root
         group: root
         mode: 0644
     loop: "{{ range(0,51,1)|list|zip(range(3,250,3))|list }}"

#- hosts: load-4.poc4.maxta.com

#  tasks:

#   - name: create config files for the containers
#     template:
#         src: templates/DriverConfig.txt.j2
#         dest: /root/dsmysqldriver/DriverConfig.txt.{{ item.0 }}
#         owner: root
#         group: root
#         mode: 0644
#     loop: "{{ range(0,51,1)|list|zip(range(4,250,3))|list }}"


